-- Populate event-specific success patterns for Biktarvy
INSERT INTO content_success_patterns (
  brand_id,
  pattern_name,
  pattern_type,
  pattern_description,
  pattern_rules,
  sample_size,
  avg_performance_lift,
  confidence_score,
  applicable_audiences,
  applicable_channels,
  validation_status
) VALUES
-- Conference booth + podium patterns
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Booth + Podium Combo Excellence',
  'event_combination',
  'Combining booth presence with podium presentation drives 45% higher lead generation and follow-up engagement compared to booth-only events',
  '{"activities": ["booth", "podium"], "minLift": 45, "successFactors": ["pre-event email", "evidence-dense slides", "leave-behind materials", "post-event follow-up"]}'::jsonb,
  28,
  45.3,
  89,
  ARRAY['Physician-Specialist', 'Pharmacist'],
  ARRAY['event', 'email'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Pre-Event + Post-Event Email Journey',
  'event_sequence',
  'Sending targeted email 3-5 days before event and follow-up within 48 hours increases engagement by 67% and conversion by 34%',
  '{"sequence": ["pre_event_email", "event", "post_event_email"], "timingDays": {"pre": -4, "post": 2}, "minLift": 67}'::jsonb,
  42,
  67.2,
  92,
  ARRAY['Physician-Specialist', 'Pharmacist', 'Nurse-NP-PA'],
  ARRAY['email', 'event'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'KOL Podium with Clinical Leave-Behind',
  'event_element_combination',
  'KOL-targeted podium presentations with evidence-dense leave-behind materials drive 38% higher follow-up conversion and 52% better recall',
  '{"elements": [{"type": "podium", "audience": "KOL"}, {"type": "leave_behind", "content": "clinical_evidence"}], "minLift": 38}'::jsonb,
  35,
  38.7,
  86,
  ARRAY['Physician-Specialist'],
  ARRAY['event', 'rep_presentation'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Evidence-Dense Slides for Specialists',
  'event_content_format',
  'Specialist audiences (ID, Infectious Disease, HIV experts) show 25% better recall and 31% higher engagement with data-heavy presentations featuring study results and statistical evidence',
  '{"contentStyle": "evidence_dense", "audience": "specialist", "elements": ["clinical_data", "statistical_evidence", "study_results"], "minLift": 25}'::jsonb,
  47,
  25.4,
  91,
  ARRAY['Physician-Specialist'],
  ARRAY['event', 'rep_presentation'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Advisory Board Pre-Read Excellence',
  'event_preparation',
  'Advisory boards with pre-distributed clinical briefing materials 7-10 days prior show 58% better discussion quality and 43% higher post-event action items',
  '{"eventType": "advisory_board", "preparation": "clinical_briefing", "timingDays": -8, "minLift": 58}'::jsonb,
  19,
  58.1,
  84,
  ARRAY['Physician-Specialist'],
  ARRAY['event', 'email'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Launch Event Multi-Touch Strategy',
  'event_launch',
  'Product launch events with 4+ touchpoints (invitation, reminder, event, follow-up, rep visit) drive 72% higher prescriber adoption within 90 days',
  '{"eventType": "launch", "touchpoints": 4, "sequence": ["invitation", "reminder", "event", "follow-up", "rep_visit"], "minLift": 72}'::jsonb,
  23,
  72.5,
  88,
  ARRAY['Physician-Specialist', 'Pharmacist'],
  ARRAY['event', 'email', 'rep_presentation'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Regional Conference Booth Optimization',
  'event_channel_mix',
  'Regional conferences with booth + digital sales aid + rep scheduling show 51% higher meeting conversion compared to booth-only presence',
  '{"eventType": "regional_conference", "elements": ["booth", "digital_sales_aid", "rep_scheduling"], "minLift": 51}'::jsonb,
  31,
  51.2,
  87,
  ARRAY['Physician-Specialist', 'Pharmacist', 'Nurse-NP-PA'],
  ARRAY['event', 'rep_presentation'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Patient-Focused Event Materials',
  'event_audience_match',
  'Patient education events with simplified language, visual aids, and actionable next steps drive 44% higher material retention and 29% more follow-up questions',
  '{"audience": "patient", "contentStyle": "simplified", "elements": ["visual_aids", "actionable_steps", "q_and_a"], "minLift": 44}'::jsonb,
  26,
  44.3,
  85,
  ARRAY['Patient-Newly Diagnosed', 'Patient-Treatment Experienced'],
  ARRAY['event', 'web'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Rep-Enabled Booth Follow-Up',
  'event_rep_coordination',
  'Events where booth leads are immediately shared with reps for 48-hour follow-up show 63% higher conversion to scheduled appointments',
  '{"coordination": "booth_to_rep", "followUpHours": 48, "minLift": 63}'::jsonb,
  37,
  63.4,
  90,
  ARRAY['Physician-Specialist', 'Pharmacist'],
  ARRAY['event', 'rep_presentation'],
  'validated'
),
(
  '225d6bbc-c663-462f-86a8-21886bc40047',
  'Virtual Event Engagement Bundle',
  'event_virtual',
  'Virtual events with interactive Q&A, downloadable resources, and post-event survey drive 39% higher engagement than presentation-only format',
  '{"eventType": "virtual", "interactive": true, "elements": ["q_and_a", "downloadable_resources", "survey"], "minLift": 39}'::jsonb,
  29,
  39.1,
  83,
  ARRAY['Physician-Specialist', 'Pharmacist', 'Nurse-NP-PA'],
  ARRAY['web', 'email'],
  'validated'
);