// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Removed: import type { Database } from './types'; (TypeScript type import)

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// NOTE: If you encounter 'supabaseUrl is required' error, 
// the environment variables VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY 
// are missing or undefined. Check your .env file and Vite configuration.

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Removed: <Database> type argument
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});